version: '3.9'
services:
  db:
    image: postgis/postgis:16-3.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farm_api_development
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
        RAILS_ENV: development
        FARM_API_DATABASE_USERNAME: user
        FARM_API_DATABASE_PASSWORD: password
        DATABASE_URL: "postgis://user:password@db:5432/farm_api_development"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
