default: &default
  adapter: postgis
  encoding: unicode
  host: localhost
  schema_search_path: public
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: farm_api_development
  username: <%= ENV['FARM_API_DATABASE_USERNAME'] %>
  password: <%= ENV['FARM_API_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: farm_api_test
  username: <%= ENV['FARM_API_DATABASE_USERNAME'] %>
  password: <%= ENV['FARM_API_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: farm_api_production
  username: farm_api
  password: <%= ENV["FARM_API_DATABASE_PASSWORD"] %>
